### ISSUE TITLE
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity

### ISSUE THREAD

**Issue by JihaoLee** [eriklindernoren/PyTorch-YOLOv3#110]
Hi! I have some problems about this 'loss = model(imgs, targets)' in train.py
Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1578, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1015, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/workspace/YOLOv3_pytorch/train.py", line 85, in <module>
    loss = model(imgs, targets)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/YOLOv3_pytorch/models.py", line 259, in forward
    x, *losses = module[0](x, targets)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/YOLOv3_pytorch/models.py", line 202, in forward
    loss_cls = (1 / nB) * self.ce_loss(pred_cls[mask], torch.argmax(tcls[mask], dim=1))
  File "/usr/local/lib/python3.5/dist-packages/torch/functional.py", line 533, in argmax
    return torch._argmax(input, dim, keepdim)
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity
My environment is python3.5.2, torch1.0.0, GPU K80, linux

**Comment by JihaoLee** [comment]
When I debugged the program, I saw 
`tcls[mask] = tensor([], device='cuda:0', size=(0, 80), dtype=torch.int64)`.
So, torch.argmax() cannot be executed.
This is In models.py line202, 
`loss_cls = (1 / nB) * self.ce_loss(pred_cls[mask], torch.argmax(tcls[mask], 1))`

**Comment by stmoon** [comment]
I have the same error... Do you solve this problem?

**Comment by JihaoLee** [comment]
>           I have the same error... Do you solve this problem?
[https://github.com/bobo0810/PyTorch-YOLOv3-master](url)
This program can be executed, but the loss of x, y, w, h and cls is 0. I do not know why. If you have time, you can fix it. I'll look at the code in detail in two weeks. If you are not busy at that time, we can discuss it together.

**Comment by stmoon** [comment]
@JihaoLee . Yes.. I tried to train again. Actually, I tried to train with other datasets (visdrone). In this case, it worked. however, it doesn't find any object. :-(

**Comment by JihaoLee** [comment]
Which program do you use?  What is the value of loss function?

**Comment by horngjason** [comment]
@JihaoLee 
I met the same issue as you two did in the last days. Yet as searching for the solution to deal with this situation, I found the answer to this difficulty. Please refer to ShiinaMitsuki's last comment in [https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/79](url).

**COCO** is the dataset I tried; **yolov3.cfg** as well as **yolov3.weights** are config files I used ( for, tiny version, some modification need to be done first. Possible answer can be found in this forum as well ). No matter where you put the two folders ( "images" and "labels" ) , just be sure to keep in that kind of structure as ShiinaMitsuki's last comment.

By the way, I also enlarged two values, batch and subdivisions, in yolov3.cfg. Instead of 1 and 1 respectively, I changed either of them to be 16 and 16. In 1 and 1 setting, you will still meet a runtimeError. That's why please remember to modify these two values before accessing sparsity.py.

*Here just share the solution to make the code work. Nothing to do the confirmation that the training results is correct as good as Darknet provided.

**Comment by JihaoLee** [comment]
@horngjason Ok, thank you~ I will have a try

**Comment by mrkieumy** [comment]
Dear @horngjason,
according to the last comment of answer for #79, what do we put on the annotations folder? Because every image we have an annotation file. So I put images in images/train, and I put annotations in labels/train. Is that right?
Thank you.

**Comment by kangliangc** [comment]
Same stuff happened here..... I also spent hours on this and nothing works out.

**Comment by JihaoLee** [comment]
@kangliangc  Please modify utils/datasets.py line 53 to check whether the path of your dataset is replaced correctly.

**Comment by kangliangc** [comment]
@JihaoLee Thanks for the reply, and that is indeed the point caused the issue. I found my label path is not correct.

**Comment by yanghedada** [comment]
I train  own data . My data format is voc and use  this code [voc_label.py](https://pjreddie.com/media/files/voc_label.py) for pytorch training ., but I get ：

RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity。

then：
I modify utils/datasets.py line 53 ，‘images’  to  ‘’JPEGImages。everything is ok

**Comment by kangliangc** [comment]
So basically this issue is caused by empty input data. To anyone has the same issue, please check whether your model has correct inputs and labels.

**Comment by AntoineGerardeaux** [comment]
@yanghedada for me that was in the parse_config.py i just have to change "images" to "JPEGImages" line 41 : (self.label_files = [path.replace('JPEGImages', 'labels').replace('.png', ........)

Thank you !!!

**Comment by sirajunnabi** [comment]
After preprocessing of train.txt and val.txt files with the generation of labels annotation files, you must have two folders before executing the train.py:
1. images: all mixed class/object images should be in this folder but no class/object folder
2. labels: all mixed image labels text files of every object should be in this folder but it should not contain any subfolder (of any class or object) in it.

**Comment by aedirn** [comment]
I had this exact same problem, and dove deeper into it based on @JihaoLee 's comment:

> When I debugged the program, I saw
> `tcls[mask] = tensor([], device='cuda:0', size=(0, 80), dtype=torch.int64)`.
> So, torch.argmax() cannot be executed.

The size (0,80) is what's breaking argmax which expects a value of at least 1 in every size() element. The 80 comes from the number of classes you are using, and the 0 comes from the fact that **there are no ground-truth bounding boxes in the current batch.** That's the root of the problem. As seen in the comments above, people were getting that from data loading errors like wrong directory name, as from @yanghedada : 

> I modify utils/datasets.py line 53 ，‘images’ to ‘’JPEGImages。everything is ok

Or from correct data loading, but they needed to increase the batch size so that the batch would include at least one input image that contains at least one bounding box, from @horngjason :

> By the way, I also enlarged two values, batch and subdivisions, in **yolov3.cfg.** Instead of 1 and 1 respectively, I changed either of them to be 32 and 16. In **"1 and 1"** setting, you will still encounter a runtimeError. 

So we know that this happens when the training image batch contains no bounding boxes. 
The question now is what to do when this happens? 
We can detect this happening with the following check, just before the bugged cls_loss calculation: 
`if tcls[mask].size()[0] == 0:`

In the case where `pred_cls[mask].size()[0] == 0`, that means that our network has successfully predicted 0 bounding boxes, which is a True Negative (or multiple True Negatives). We should reward that (I think) by setting the return loss to 0.0. 

But what about the case where `pred_cls[mask].size()[0] != 0`? Our network has predicted bounding boxes where there are none in the ground-truth training data. How do we measure the class loss here? Does anyone have a good idea?

**Comment by Hukongtao** [comment]
> So basically this issue is caused by empty input data. To anyone has the same issue, please check whether your model has correct inputs and labels.

I got the same error,and the reason is that the image have no bboxes

**Comment by yufanxin** [comment]
直接说中文不行吗，这层楼都是中国人，我服了

**Comment by ch-hristov** [comment]
for anyone who ended up recently here: this happened to me because the name of the label folder I used wasn't the one utils/datasets.py was expecting. I named my images folder as "images" and my labels folder as "labels". That fixed this error.
