### ISSUE TITLE
fine tune on another dataset

### ISSUE THREAD

**Issue by mehrdadazizi72** [eriklindernoren/PyTorch-YOLOv3#118]
Hi
I want to fine tune pre-trained model on open image class
i changed yolo3.cfg and creat .data file like coco.data
but when loading weights I got an error because of differences between the number of classes
anyone train on a dataset with more than coco dataset classes?

**Comment by fourth-archive** [comment]
It sounds like you want to train on your own dataset, but start from some pretrained weights. This is what darknet53 is for. The repo below allows you to train your own custom network, and automatically starts training from darknet53 rather than from scratch. You need to be careful to rewrite your cfg and data files to accomodate your custom class count, etc, as you mention though of course.
https://github.com/ultralytics/yolov3

**Comment by claire-s11** [comment]
Hi @mehrdadazizi72 , I'm trying to fine-tune it on open image dataset as well. How did it go?
