### ISSUE TITLE
RuntimeError: expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by Star41** [eriklindernoren/PyTorch-YOLOv3#182]
I train on COCO using a Darknet-53 backend pretrained on ImageNet, and have this problem.
![QQ截图20190519144543](https://user-images.githubusercontent.com/37405516/57978725-1844b980-7a45-11e9-9460-602b95fed696.png)

**Comment by KtK99** [comment]
Were you able to fix this problem? I am getting this error from this line samples = collate_fn([dataset[i] for i in batch_indices]), which is calling a custom collate_fn in Util

**Comment by freehome1** [comment]
I have the same problem, have you slove it?

**Comment by KtK99** [comment]
I found that there is actually no bug in the code. It runs smoothly, but the problem is in the files containing the list of file paths, in my case there was no ":" after C drive so I simply added a line after each line read.

**Comment by mama110** [comment]
For me, this is because the invalid label file path. I modify the label path in datasets.py and it works.

**Comment by z-huabao** [comment]
In my case, got error when val, and the val label `data/coco/labels/val2014/**.txt` not exists

**Comment by WeeshawChen** [comment]
> For me, this is because the invalid label file path. I modify the label path in datasets.py and it works.

Would you please tell me how did you modify the label path in datasets.py? I got the same issue,but no idea how to modify my label path

**Comment by WeeshawChen** [comment]
> > For me, this is because the invalid label file path. I modify the label path in datasets.py and it works.
> 
> Would you please tell me how did you modify the label path in datasets.py? I got the same issue,but no idea how to modify my label path @mama110

And I figured it out by modifying my images in folder(images), cuz my number of images doesn't equal to my number of labels.

**Comment by ouening** [comment]
I met this problem when I use PASCAL VOC datasets. My solution is:
1. use https://pjreddie.com/media/files/voc_label.py to vonvert psacal format to yolo format
2. modifiy **line 67 in file datasets.py**: replace `path.replace("images", "labels").replace(".png", ".txt").replace(".jpg", ".txt")` with `path.replace("JPEGImages", "labels").replace(".png", ".txt").replace(".jpg", ".txt")` because PASCAL VOC images were stored in `JPEGImages` directory, the default is `images` directory ( if we use custom datasets)

the important points are:
1. convert other label format (like pascal , coco) to yolo format 
2. make sure that the number of images and its corresponding label are the same

**Comment by garyliu0816** [comment]
I think i have solve this problem.
Here is the code to insert
in dataset.py \_\_getitem__:
```
img_path = self.img_files[index % len(self.img_files)].rstrip()
img_path_list = list(img_path)
img_path_list.insert(2, ':')
img_path = "".join(img_path_list)
img_path = img_path[1:]
```
And same to label
```
label_path = self.label_files[index % len(self.label_files)].rstrip()
label_path_list = list(label_path)
label_path_list.insert(2, ':')
label_path = "".join(label_path_list)
label_path = label_path[1:]
```

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
