### ISSUE TITLE
When and why use  Tensor.data ?

### ISSUE THREAD

**Issue by GlassyWing** [eriklindernoren/PyTorch-YOLOv3#211]
I'm a torch beginner, I don't know why use Tensor.data, Isn't it cutting off gradient propagation? Has anyone told me why?
https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/47b7c912877ca69db35b8af3a38d6522681b3bb3/models.py#L166

**Comment by LinglanZhao** [comment]
I think using Tensor.data do cut off gradient propagation. However, in this case, these Tensor.data(s) are used to form **pred_boxes** which has nothing to do with the gradient of the loss for back propagation. There are two main uses of pred_boxes:  
1.  Forming **output** which will be used for inference (instead of **total_loss** to back propagate gradients).
2. Feeding into the function **build_targets()** to build **_ground truth labels_** and to compute **iou_scores**.  

As is shown above, neither of the uses will affect the gradient propagation. @GlassyWing

**Comment by GlassyWing** [comment]
Yes, pred_boxes is no longer involved in the back propagation process. Thank you very much for your explanation.

**Comment by GlassyWing** [comment]
> I think using Tensor.data do cut off gradient propagation. However, in this case, these Tensor.data(s) are used to form **pred_boxes** which has nothing to do with the gradient of the loss for back propagation. There are two main uses of pred_boxes:
> 
> 1. Forming **output** which will be used for inference (instead of **total_loss** to back propagate gradients).
> 2. Feeding into the function **build_targets()** to build **_ground truth labels_** and to compute **iou_scores**.
> 
> As is shown above, neither of the uses will affect the gradient propagation. @GlassyWing

Yes, pred_boxes is no longer involved in the back propagation process. Thank you very much for your explanation.
