### ISSUE TITLE
ValueError in test.py

### ISSUE THREAD

**Issue by cheremushkin** [eriklindernoren/PyTorch-YOLOv3#306]
After the object detection in the end of the epoch I'm constantly receiving this error (with my own dataset which I made according to the manual):

```
Traceback (most recent call last):
  File "train.py", line 160, in <module>
    batch_size=8,
  File "/home/cheremushkin/PyTorch-YOLOv3/test.py", line 53, in evaluate
    true_positives, pred_scores, pred_labels = [np.concatenate(x, 0) for x in list(zip(*sample_metrics))]
ValueError: not enough values to unpack (expected 3, got 0)
```

Any suggestions?

**Comment by lixingang** [comment]
refer to #178

**Comment by fnando1995** [comment]
Hello, this problems is due unpacking at the initials epochs.
Take a look at your conf_thresh, 0.5, if in the frist epoch there are no predictions/outputs that have a confidence over 0.5, sample_metrics will be an empty list, so it cant be unpacked:

`true_positives, pred_scores, pred_labels = [np.concatenate(x, 0) for x in list(zip(*sample_metrics))]`

But if you put a condition over that line, the problem will dismiss maybe at the second, or even third epoch. Because is almost sure that al least one predictions confidence will have over conf_thresh (at my experiments:0.5).


Hope this help for you or any other.


@eriklindernoren maybe one new pull with this. :)

**Comment by nanhui69** [comment]
yeah ! I meet with the same problem? does anyone has one way to it?

**Comment by angelrodriguez5** [comment]
To avoid changes in other parts of the code I just checked that sample metrics is not empty. If it is empty I just fill it with zeros. Not sure if this is the best solution but it works for me.


    if (len(sample_metrics) == 0):
        #Dummy metrics
        sample_metrics = [[[0],[0], torch.Tensor([0]), torch.Tensor([0])]]


As for the types I just checked the type of the components of sample_metrics and replicated them.

**Comment by Flova** [comment]
@angelrodriguez5 could you provide a pull request with this fix?

**Comment by Flova** [comment]
Also closing due to duplication of #178
