### ISSUE TITLE
detect.py

### ISSUE THREAD

**Issue by xiaotian3** [eriklindernoren/PyTorch-YOLOv3#311]
(4) Image: 'data/test/bdaqm0909_1001.jpg'
tensor(1.)
Traceback (most recent call last):
  File "detect.py", line 118, in <module>
    print("\t+ Label: %s, Conf: %.5f" % (classes[int(cls_pred)], cls_conf.item()))
IndexError: list index out of range

**Comment by csdyang** [comment]
遇到同样的问题解决了吗

**Comment by SahadevPoudel** [comment]
Did you solve this issue?

**Comment by wmj1238** [comment]
Did you solve this issue? @SahadevPoudel @csdyang @xiaotian3

**Comment by jfxjjfxj** [comment]
This problem is because the parameters are not loaded correctly when loading your own training model.

To use on the custom dataset run:

python3 detect.py 

--image_folder
data/samples/
--class_path
data/custom/classes.names
--model_def
config/yolov3-custom.cfg
--weights_path
checkpoints/yolov3_ckpt_100.pth    #Use the model you trained

**Comment by jfxjjfxj** [comment]
@SahadevPoudel @csdyang @wmj1238

**Comment by rosagradilla19** [comment]
I had the same issue.. make sure your classes.names has an extra empty line at the end! this fixed it for me

**Comment by biuwang90098** [comment]
> 我有同样的问题..确保你的 classes.names 最后有一个额外的空行！这为我修好了

I had this problem, thanks!

**Comment by biuwang90098** [comment]
> I had the same issue.. make sure your classes.names has an extra empty line at the end! this fixed it for me

I had this problem, now it's solved, thanks!
