### ISSUE TITLE
Evaluating Model is slow

### ISSUE THREAD

**Issue by mama110** [eriklindernoren/PyTorch-YOLOv3#355]
Evaluating Model is too slow, can anyone help me?

**Comment by priteshgohil** [comment]
Same problem here.

**Comment by tmvhs1004** [comment]
me too..

**Comment by recusant7** [comment]
me too...

**Comment by linliu1127** [comment]
me too...

**Comment by meng-zha** [comment]
The default conf_thres is 0.001, which means NMS module needs to process all predictions.
The evaluation while training sets the conf_thres 0.5.
If want fast inference, change the conf_thres.

**Comment by jaagut** [comment]
For the first epochs, you have too many predictions due to the random initialization. You can also get many predictions with a unsuitable conf_thres as @meng-zha mentioned.
When too many predictions, NMS gets quite expensive and takes time. This should be fixed with the timeout for the nms that was introduced some time ago.

Same as  #415
