### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../coco/images/val2014/COCO_val2014_000000000164.jpg'

### ISSUE THREAD

**Issue by xwf12345678** [eriklindernoren/PyTorch-YOLOv3#372]
When I run the test.py , I fail.

**Comment by Einstellung** [comment]
I have the same error as you, finally i solve the problem, try this code for 5k.part and trainvalno5k.part

`paste <(awk "{print \"$PWD\"}" <5k.part) 5k.part | tr -d '\t' > 5k.txt

paste <(awk "{print \"$PWD\"}" <trainvalno5k.part) trainvalno5k.part | tr -d '\t' > trainvalno5k.txt
`

**Comment by xwf12345678** [comment]
Sorry, I don't understand what do you mean.
@Einstellung

**Comment by Einstellung** [comment]
I mean,  for example. 5k.part is in coco file. In coco file, you can open shell and then input the command:
```sh
paste <(awk "{print \"$PWD\"}" <5k.part) 5k.part | tr -d '\t' > 5k.txt

paste <(awk "{print \"$PWD\"}" <trainvalno5k.part) trainvalno5k.part | tr -d '\t' > trainvalno5k.txt
```

**Comment by xiaoyuzhu666** [comment]
> I mean, for example. 5k.part is in coco file. In coco file, you can open shell and then input the command:
> 
> ```shell
> paste <(awk "{print \"$PWD\"}" <5k.part) 5k.part | tr -d '\t' > 5k.txt
> 
> paste <(awk "{print \"$PWD\"}" <trainvalno5k.part) trainvalno5k.part | tr -d '\t' > trainvalno5k.txt
> ```

I did it,but the error still exist.  ~_~
Detecting objects:   0%|          | 0/625 [00:00<?, ?it/s]Traceback (most recent call last):
  File "E:/PyTorch-YOLOv3-master/test.py", line 98, in <module>
    batch_size=8,
  File "E:/PyTorch-YOLOv3-master/test.py", line 36, in evaluate
    for batch_i, (_, imgs, targets) in enumerate(tqdm.tqdm(dataloader, desc="Detecting objects")):
  File "D:\Anaconda\envs\PyTorch-YOLOv3-master\lib\site-packages\tqdm\std.py", line 1108, in __iter__
    for obj in iterable:
  File "D:\Anaconda\envs\PyTorch-YOLOv3-master\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "D:\Anaconda\envs\PyTorch-YOLOv3-master\lib\site-packages\torch\utils\data\dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "D:\Anaconda\envs\PyTorch-YOLOv3-master\lib\site-packages\torch\utils\data\dataloader.py", line 881, in _process_data
    data.reraise()
  File "D:\Anaconda\envs\PyTorch-YOLOv3-master\lib\site-packages\torch\_utils.py", line 394, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Anaconda\envs\PyTorch-YOLOv3-master\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Anaconda\envs\PyTorch-YOLOv3-master\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda\envs\PyTorch-YOLOv3-master\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\PyTorch-YOLOv3-master\utils\datasets.py", line 86, in __getitem__
    img = transforms.ToTensor()(Image.open(img_path).convert('RGB'))
  File "D:\Anaconda\envs\PyTorch-YOLOv3-master\lib\site-packages\PIL\Image.py", line 2809, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/e/PyTorch-YOLOv3-master/data/coco/images/val2014/COCO_val2014_000000000164.jpg'

Detecting objects:   0%|          | 0/625 [00:06<?, ?it/s]

Process finished with exit code 1

**Comment by cccccccccy** [comment]
> > I mean, for example. 5k.part is in coco file. In coco file, you can open shell and then input the command:
> > ```shell
> > paste <(awk "{print \"$PWD\"}" <5k.part) 5k.part | tr -d '\t' > 5k.txt
> > 
> > paste <(awk "{print \"$PWD\"}" <trainvalno5k.part) trainvalno5k.part | tr -d '\t' > trainvalno5k.txt
> > ```
> 
> I did it,but the error still exist. ~_~
> Detecting objects: 0%| | 0/625 [00:00<?, ?it/s]Traceback (most recent call last):
> File "E:/PyTorch-YOLOv3-master/test.py", line 98, in
> batch_size=8,
> File "E:/PyTorch-YOLOv3-master/test.py", line 36, in evaluate
> for batch_i, (_, imgs, targets) in enumerate(tqdm.tqdm(dataloader, desc="Detecting objects")):
> File "D:\Anaconda\envs\PyTorch-YOLOv3-master\lib\site-packages\tqdm\std.py", line 1108, in **iter**
> for obj in iterable:
> File "D:\Anaconda\envs\PyTorch-YOLOv3-master\lib\site-packages\torch\utils\data\dataloader.py", line 345, in **next**
> data = self._next_data()
> File "D:\Anaconda\envs\PyTorch-YOLOv3-master\lib\site-packages\torch\utils\data\dataloader.py", line 856, in _next_data
> return self._process_data(data)
> File "D:\Anaconda\envs\PyTorch-YOLOv3-master\lib\site-packages\torch\utils\data\dataloader.py", line 881, in _process_data
> data.reraise()
> File "D:\Anaconda\envs\PyTorch-YOLOv3-master\lib\site-packages\torch_utils.py", line 394, in reraise
> raise self.exc_type(msg)
> FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
> Original Traceback (most recent call last):
> File "D:\Anaconda\envs\PyTorch-YOLOv3-master\lib\site-packages\torch\utils\data_utils\worker.py", line 178, in _worker_loop
> data = fetcher.fetch(index)
> File "D:\Anaconda\envs\PyTorch-YOLOv3-master\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in fetch
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "D:\Anaconda\envs\PyTorch-YOLOv3-master\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "E:\PyTorch-YOLOv3-master\utils\datasets.py", line 86, in **getitem**
> img = transforms.ToTensor()(Image.open(img_path).convert('RGB'))
> File "D:\Anaconda\envs\PyTorch-YOLOv3-master\lib\site-packages\PIL\Image.py", line 2809, in open
> fp = builtins.open(filename, "rb")
> FileNotFoundError: [Errno 2] No such file or directory: '/e/PyTorch-YOLOv3-master/data/coco/images/val2014/COCO_val2014_000000000164.jpg'
> 
> Detecting objects: 0%| | 0/625 [00:06<?, ?it/s]
> 
> Process finished with exit code 1

**Comment by cccccccccy** [comment]
> > 我的意思是，例如。5k.part在coco文件中。在coco文件中，可以打开shell，然后输入命令：
> > ```shell
> > 粘贴<（ awk “ {print \” $ PWD \“ } ”  < 5k.part ） 5k.part | tr -d ' \ t '  > 5k.txt
> > 
> > 粘贴<（ awk “ {print \” $ PWD \“ } ”  << trainvalno5k.part ） trainvalno5k.part | tr -d ' \ t '  > trainvalno5k.txt
> > ```
> 
> 我做到了，但是错误仍然存​​在。 ~_~
> 检测物体：0％| | 0/625 [00:00 <?,？it / s]跟踪（最近一次通话最近）：
> 文件“ E：/PyTorch-YOLOv3-master/test.py”，第98行，
> batch_size = 8，
> 文件“ E” ：/PyTorch-YOLOv3-master/test.py“，第36行，
> 用于枚举（tqdm.tqdm（dataloader，desc =” Detecting objects“））中的batch_i，（_，imgs，目标）评估：
> 文件“ D： \蟒蛇\ ENVS \ PyTorch-YOLOv3主\ LIB \站点包\ tqdm \ std.py “线1108，在**ITER**
> 在迭代的OBJ：
> 文件” d：\蟒蛇\ ENVS \ PyTorch-YOLOv3主\ LIB \ site-packages \ torch \ utils \ data \ dataloader.py“，第345行，**在下一个**
> 数据= self._next_data（）
> 文件” D：\ Anaconda \ envs \ PyTorch-YOLOv3-master \ lib \ site-packages \ torch \ utils \ data \ dataloader。
> 返回self._process_data（data）
> 文件_process_data
> data.reraise（）
> 文件中的第881行“ D：\ Anaconda \ envs \ PyTorch-YOLOv3-master \ lib \ site-packages \ torch \ utils \ data \ dataloader.py” “ D：\ Anaconda \ envs \ PyTorch-YOLOv3-master \ lib \ site-packages \ torch_utils.py”，行394，重新
> 引发self.exc_type（msg）
> FileNotFoundError：在DataLoader工作进程0中捕获FileNotFoundError。
> 原始回溯（最近一次通话）：
> 文件_worker_loop数据中的文件“ D：\ Anaconda \ envs \ PyTorch-YOLOv3-master \ lib \ site-packages \ torch \ utils \ data_utils \ worker.py”，第178行，
> 数据= fetcher.fetch（索引）
> 文件“ D：\ Anaconda \ envs \ PyTorch-YOLOv3-master \ lib \ site-packages \ torch \ utils \ data_utils \ fetch.py​​”，第44行，在抓取中
> 数据= [identity_batched_index中idx的[self.dataset [idx]]
> 文件“ D：\ Anaconda \ envs \ PyTorch-YOLOv3-master \ lib \ site-packages \ torch \ utils \ data_utils \ fetch.py​​”，第44行，
> 数据= [self.dataset [IDX用于IDX在possibly_batched_index]
> 文件“E：\ PyTorch-YOLOv3主\ utils的\ datasets.py”，线86，在**的GetItem**
> IMG = transforms.ToTensor（）（Image.open（img_path ）.convert（'RGB'））
> 文件“ D：\ Anaconda \ envs \ PyTorch-YOLOv3-master \ lib \ site-packages \ PIL \ Image.py”，行2809，在打开时
> fp = Builtins.open（filename， “ rb”）
> FileNotFoundError：[错误2]没有这样的文件或目录：'/e/PyTorch-YOLOv3-master/data/coco/images/val2014/COCO_val2014_000000000164.jpg'
> 
> 检测物体：0％| | 0/625 [00:06 <?,？it / s]
> 
> 流程以退出代码1完成

perhaps your system is win10 , so it cannot find '/e/PyTorch-YOLOv3-master/data/coco/images/val2014/COCO_val2014_000000000164.jpg'
try change it to 'E:/PyTorch-YOLOv3-master/data/coco/images/val2014/COCO_val2014_000000000164.jpg'

**Comment by Cecilia-Ling** [comment]
> > > 我的意思是，例如。5k.part在coco文件中。在coco文件中，可以打开shell，然后输入命令：
> > > ```shell
> > > 粘贴<（ awk “ {print \” $ PWD \“ } ”  < 5k.part ） 5k.part | tr -d ' \ t '  > 5k.txt
> > > 
> > > 粘贴<（ awk “ {print \” $ PWD \“ } ”  << trainvalno5k.part ） trainvalno5k.part | tr -d ' \ t '  > trainvalno5k.txt
> > > ```
> > 
> > 
> > 我做到了，但是错误仍然存​​在。 ~_~
> > 检测物体：0％| | 0/625 [00:00 <?,？it / s]跟踪（最近一次通话最近）：
> > 文件“ E：/PyTorch-YOLOv3-master/test.py”，第98行，
> > batch_size = 8，
> > 文件“ E” ：/PyTorch-YOLOv3-master/test.py“，第36行，
> > 用于枚举（tqdm.tqdm（dataloader，desc =” Detecting objects“））中的batch_i，（_，imgs，目标）评估：
> > 文件“ D： \蟒蛇\ ENVS \ PyTorch-YOLOv3主\ LIB \站点包\ tqdm \ std.py “线1108，在**ITER**
> > 在迭代的OBJ：
> > 文件” d：\蟒蛇\ ENVS \ PyTorch-YOLOv3主\ LIB \ site-packages \ torch \ utils \ data \ dataloader.py“，第345行，**在下一个**
> > 数据= self._next_data（）
> > 文件” D：\ Anaconda \ envs \ PyTorch-YOLOv3-master \ lib \ site-packages \ torch \ utils \ data \ dataloader。
> > 返回self._process_data（data）
> > 文件_process_data
> > data.reraise（）
> > 文件中的第881行“ D：\ Anaconda \ envs \ PyTorch-YOLOv3-master \ lib \ site-packages \ torch \ utils \ data \ dataloader.py” “ D：\ Anaconda \ envs \ PyTorch-YOLOv3-master \ lib \ site-packages \ torch_utils.py”，行394，重新
> > 引发self.exc_type（msg）
> > FileNotFoundError：在DataLoader工作进程0中捕获FileNotFoundError。
> > 原始回溯（最近一次通话）：
> > 文件_worker_loop数据中的文件“ D：\ Anaconda \ envs \ PyTorch-YOLOv3-master \ lib \ site-packages \ torch \ utils \ data_utils \ worker.py”，第178行，
> > 数据= fetcher.fetch（索引）
> > 文件“ D：\ Anaconda \ envs \ PyTorch-YOLOv3-master \ lib \ site-packages \ torch \ utils \ data_utils \ fetch.py​​”，第44行，在抓取中
> > 数据= [identity_batched_index中idx的[self.dataset [idx]]
> > 文件“ D：\ Anaconda \ envs \ PyTorch-YOLOv3-master \ lib \ site-packages \ torch \ utils \ data_utils \ fetch.py​​”，第44行，
> > 数据= [self.dataset [IDX用于IDX在possibly_batched_index]
> > 文件“E：\ PyTorch-YOLOv3主\ utils的\ datasets.py”，线86，在**的GetItem**
> > IMG = transforms.ToTensor（）（Image.open（img_path ）.convert（'RGB'））
> > 文件“ D：\ Anaconda \ envs \ PyTorch-YOLOv3-master \ lib \ site-packages \ PIL \ Image.py”，行2809，在打开时
> > fp = Builtins.open（filename， “ rb”）
> > FileNotFoundError：[错误2]没有这样的文件或目录：'/e/PyTorch-YOLOv3-master/data/coco/images/val2014/COCO_val2014_000000000164.jpg'
> > 检测物体：0％| | 0/625 [00:06 <?,？it / s]
> > 流程以退出代码1完成
> 
> perhaps your system is win10 , so it cannot find '/e/PyTorch-YOLOv3-master/data/coco/images/val2014/COCO_val2014_000000000164.jpg'
> try change it to 'E:/PyTorch-YOLOv3-master/data/coco/images/val2014/COCO_val2014_000000000164.jpg'

Thank you! I have solved my problem

**Comment by Zzheng-6** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Administrator/Desktop/PyTorch-YOLOv3/data/coco/images/images/train2014/COCO_train2014_000000244933.jpg' 请问一下，为什么会出现这样的错误，这张图片在数据集中是存在的，我打的路径也只有一个images，为什么会显示出现了两个images?

**Comment by Zzheng-6** [comment]
FileNotFoundError：[Errno 2]没有这样的文件或目录：'C：/Users/Administrator/Desktop/PyTorch-YOLOv3/data/coco/images/images/train2014/COCO_train2014_000000244933.jpg'请问一下，为什么会出现这样的错误，这张图片在数据集中是存在的，我打的路径也只有一个图片，为什么会显示出现了两个images文件？

**Comment by Flova** [comment]
The current master skips missing images with a warning. And coco has some missing ones.

**Comment by Zzheng-6** [comment]
So what am I supposed to do? Reload the coco dataset?
and&nbsp;&nbsp;How do I fix an error like this(when i run train.py)
thank you very much!
Because it's been bothering me for over a week


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eriklindernoren/PyTorch-YOLOv3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月4日(星期四) 晚上10:33
收件人:&nbsp;"eriklindernoren/PyTorch-YOLOv3"<PyTorch-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"两颗西柚"<1349478794@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] FileNotFoundError: [Errno 2] No such file or directory: '../coco/images/val2014/COCO_val2014_000000000164.jpg' (#372)





 
The current master skips missing images with a warning. And coco has some missing ones.

**Comment by Flova** [comment]
If I understand you right, you just need to pull the current master, run the `train.py` and ignore the warnings that some coco images are missing.

**Comment by Zzheng-6** [comment]
Yes,I use the coco dataset.
Sorry, I didn't understand what you mean too much. What should I do to "pull the current master", I not only have the problem of images loss, I also have the problem as shown in the picture.When I run train.py,I failed.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eriklindernoren/PyTorch-YOLOv3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月5日(星期五) 晚上11:06
收件人:&nbsp;"eriklindernoren/PyTorch-YOLOv3"<PyTorch-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"两颗西柚"<1349478794@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] FileNotFoundError: [Errno 2] No such file or directory: '../coco/images/val2014/COCO_val2014_000000000164.jpg' (#372)





 
If I understand you right, you just need to pull the current master, run the train.py and ignore the warnings that some coco images are missing.

**Comment by Flova** [comment]
You need to download the newest version of this repo. This is done by running `git pull` using git. It runs if you do that because missing labels are now handled properly.

**Comment by Zzheng-6** [comment]
If I understand you correctly,I need to download Git,and do the same as on the website I searched, right?
https://www.runoob.com/git/git-pull.html
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eriklindernoren/PyTorch-YOLOv3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月6日(星期六) 中午1:15
收件人:&nbsp;"eriklindernoren/PyTorch-YOLOv3"<PyTorch-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"两颗西柚"<1349478794@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] FileNotFoundError: [Errno 2] No such file or directory: '../coco/images/val2014/COCO_val2014_000000000164.jpg' (#372)





 
You need to download the newest version of this repo. This is done by running git pull using git. It runs if you do that because missing labels are now handled properly.

**Comment by Flova** [comment]
Download git here https://git-scm.com/

**Comment by Zzheng-6** [comment]
Thank you very much,I have downloaded git,I deleted the previous YOLOV3 file and download it again. I have downloaded the weight file, but I found that the download speed of coco is very slow .TAT




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eriklindernoren/PyTorch-YOLOv3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月8日(星期一) 晚上7:23
收件人:&nbsp;"eriklindernoren/PyTorch-YOLOv3"<PyTorch-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"两颗西柚"<1349478794@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] FileNotFoundError: [Errno 2] No such file or directory: '../coco/images/val2014/COCO_val2014_000000000164.jpg' (#372)





 
Download git here https://git-scm.com/

**Comment by Flova** [comment]
Yea the download takes some time. I, therefore, recommend pulling the code using git in your existing repository. This keeps your datasets without downloading them again.

**Comment by Zzheng-6** [comment]
Thank you for your suggestion. I have tried it before, but maybe because I have not used git before, I failed. I may need to spend a little time to research.
Because we signed up for a competition at school, the project needs to use YOLOv3. Now everything is only at the beginning stage. We still don’t know how to start, so we learn YOLOV3 first.
All in all, thank you very much.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eriklindernoren/PyTorch-YOLOv3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月9日(星期二) 凌晨0:07
收件人:&nbsp;"eriklindernoren/PyTorch-YOLOv3"<PyTorch-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"两颗西柚"<1349478794@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] FileNotFoundError: [Errno 2] No such file or directory: '../coco/images/val2014/COCO_val2014_000000000164.jpg' (#372)





 
Yea the download takes some time. I, therefore, recommend pulling the code using git in your existing repository. This keeps your datasets without downloading them again.

**Comment by Zzheng-6** [comment]
I take the liberty to bother you again. This error occurred when I was running train.py. How can I correct it?
---- mAP not measured (no detections found by model)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eriklindernoren/PyTorch-YOLOv3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月9日(星期二) 凌晨0:07
收件人:&nbsp;"eriklindernoren/PyTorch-YOLOv3"<PyTorch-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"两颗西柚"<1349478794@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] FileNotFoundError: [Errno 2] No such file or directory: '../coco/images/val2014/COCO_val2014_000000000164.jpg' (#372)





 
Yea the download takes some time. I, therefore, recommend pulling the code using git in your existing repository. This keeps your datasets without downloading them again.

**Comment by Flova** [comment]
This is not an error. It says that your model isn't performing good enough to make a single prediction. This is normal in the first or so epoch. 

Whats the size of your dataset and how many epochs did you train? Did you use transfer learning?

**Comment by Zzheng-6** [comment]
I used the coco dataset, and I trained for about 30 epochs, but the results were the same. There was an error during the initial training. I checked the solution is to change the dataloader's shuffle to false. I don't know if it is caused by this.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eriklindernoren/PyTorch-YOLOv3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月10日(星期三) 晚上7:31
收件人:&nbsp;"eriklindernoren/PyTorch-YOLOv3"<PyTorch-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"两颗西柚"<1349478794@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] FileNotFoundError: [Errno 2] No such file or directory: '../coco/images/val2014/COCO_val2014_000000000164.jpg' (#372)





 
This is not an error. It says that your model isn't performing good enough to make a single prediction. This is normal in the first or so epoch.
 
Whats the size of your dataset and how many epochs did you train? Did you use transfer learning?

**Comment by Flova** [comment]
Did it train well without shuffle?

**Comment by Zzheng-6** [comment]
I can’t see the training result because it keeps showing ---- mAP not measured (no detections found by model)


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eriklindernoren/PyTorch-YOLOv3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月11日(星期四) 凌晨3:15
收件人:&nbsp;"eriklindernoren/PyTorch-YOLOv3"<PyTorch-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"两颗西柚"<1349478794@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] FileNotFoundError: [Errno 2] No such file or directory: '../coco/images/val2014/COCO_val2014_000000000164.jpg' (#372)





 
Did it train well without shuffle?
