### ISSUE TITLE
empty label files

### ISSUE THREAD

**Issue by tomad01** [eriklindernoren/PyTorch-YOLOv3#408]
Will images with empty label files will be considered in training ?

**Comment by tomad01** [comment]
Yes, it seems so

**Comment by yuanyuangoo** [comment]
Hi, every time when there is empty label, it crashed. How to solve, please.

**Comment by tomad01** [comment]
I just get warnings for empty labels. Be sure you have the last updated version for numpy.
Here is the place where labels are read: 
[https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/47b7c912877ca69db35b8af3a38d6522681b3bb3/utils/datasets.py#L106](url)

**Comment by ly0303521** [comment]
> I just get warnings for empty labels. Be sure you have the last updated version for numpy.
> Here is the place where labels are read:
> [https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/47b7c912877ca69db35b8af3a38d6522681b3bb3/utils/datasets.py#L106](url)

Hi, whats your numpy version, mine is numpy-1.18.2, but it still crashed

**Comment by JoernHen** [comment]
Training run until the empty tensor.
It will be crash because from an empty tensor you can't compete the max value in utils.py line 303:
best_ious, best_n = ious.max(0)
Where best_ious is the value tensor and best_n the index tensor. 
A fix with ignore empty tensors doesn't work. The following code needs both variables.

**Comment by Flova** [comment]
It should work now
