### ISSUE TITLE
cfg file

### ISSUE THREAD

**Issue by TIMETOTIAO** [eriklindernoren/PyTorch-YOLOv3#626]
When we use train.py like train.py [-h] [--epochs EPOCHS] [--batch_size BATCH_SIZE]
                [--gradient_accumulations GRADIENT_ACCUMULATIONS]
                [--model_def MODEL_DEF] [--data_config DATA_CONFIG]
                [--pretrained_weights PRETRAINED_WEIGHTS] [--n_cpu N_CPU]
                [--img_size IMG_SIZE]
                [--checkpoint_interval CHECKPOINT_INTERVAL]
                [--evaluation_interval EVALUATION_INTERVAL]
                [--compute_map COMPUTE_MAP]
                [--multiscale_training MULTISCALE_TRAINING].
We can set the batch or other parameters. So I wonder if this train.py will use the custom.cfg file to train? or just ignore the .cfg file we modify.

**Comment by TIMETOTIAO** [comment]
In other words, can subdivision be done in this implementation?

**Comment by Flova** [comment]
training hyperparams (loss etc.) set by the cfg are currently ignored. This will be fixed soon. You can set the batch size using the cli. You can also set `--gradient_accumulations` to increase it further if your batch doesn't fit into the gpu memory anymore. This should be äquivalent to the subdivisions by darknet afaik.

**Comment by TIMETOTIAO** [comment]
> Training hyperparams (loss etc.) set by the cfg are currently ignored. This will be fixed soon. You can set the batch size using the cli. You can also set `--gradient_accumulations` to increase it further if your batch doesn't fit into the gpu memory anymore. This should be äquivalent to the subdivisions by darknet afaik.

After reading the code, I found that gradient_accumulations is after the loss, outputs = model(imgs, targets), which means it can not divide the batch into mini-batches before cuda out of memory.

**Comment by Flova** [comment]
Could you explain what you mean? I understand die gradient accumulations differently. The batch size sets how much the memory is used and the gradient accumulations accumulate multiple gradients before running the optimizer. Why should this allocate more memory?

**Comment by TIMETOTIAO** [comment]
> Could you explain what you mean? I understand die gradient accumulations differently. The batch size sets how much the memory is used and the gradient accumulations accumulate multiple gradients before running the optimizer. Why should this allocate more memory?

Thanks for the kind reply. What I mean is that the gradient_accumulations seems cannot help us to set up a higher batch size with limited GPU memory. Since the size of "dataloader" is determined by the batch_size only, the gradient_accumulations does not help to subdivide batch into multiple-mini-batches.

**Comment by Flova** [comment]
Thats true. But the gradient_accumulations describe it the other way around. Instead of subdividing you batch, you choose a small enough batch and define the batch which is passed to the optimizer as gradient_accumulations * batch_size. The latter does not affect the memory.

So instead of choosing a batch size that fits the optimizer and subdivide it into small enough mini batches for your gpu it defines the mini batches via the batch_size param and accumulates them a few times before passing them to the optimizer. This is exactly äquivalent.

In the darknet
Mini Batch(gpu) = Batch (optimizer, param) / subdivisions(param)

Here
Batch (optimizer) = Mini Batch (gpu, batch_size param)  * gradient_accumulations (param)

So we define the gpu batch instead of the optimizer batch.

**Comment by Flova** [comment]
So both approaches only load the mini batch (in the repo names batch_size) to the GPU and therefore are äquivalent in memory usage (conceptually)
