### ISSUE TITLE
Fix list initialization code location ?

### ISSUE THREAD

**Issue by 2hyes** [eriklindernoren/PyTorch-YOLOv3#642]
https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/44a3e519c0e10bea371fc08b09be09bf26ab374e/test.py#L39-L42

Shouldn't the initialization of lists(labels, sample_metrics) be in for loop? 
When in for loop, the value accumulates. It occurs that  _labels list_ have not-expected length of list so can't get the right label. Also this code seems to be a bottleneck. 

I think it should be fixed like below. Every batch has to have new empty lists. 
```
for batch_i, (_, imgs, targets) in enumerate(tqdm.tqdm(dataloader, desc="Detecting objects")): 
     labels = [] 
     sample_metrics = []  # List of tuples (TP, confs, pred) 
```

**Comment by Flova** [comment]
Thanks for your Input but the suggested changes do not work imo. The list would only be appended once and only the list content of the last iteration of the for loop would be used in further processing. This happens because the list is reset every time in the loop, but the intention of the list is to contain the metrics for all batches, not just the last one.
