### ISSUE TITLE
detect.py error:   TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by Sun-Pak** [eriklindernoren/PyTorch-YOLOv3#705]
Hi guys.
i try to detect repo.
(i don't use poetry)
sudocode : >python pytorchyolo/detect.py --images data/samples

but i got a error.
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

I don't know how i fix it.
help me.

<img width="1445" alt="aaasd" src="https://user-images.githubusercontent.com/16331744/123766821-f8f60700-d901-11eb-90ba-10102ae283c1.PNG">

**Comment by Flova** [comment]
This should be fixed by the linked pr. Try upgrading your installation. If the error still persists leave a message and I reopen.

**Comment by Sun-Pak** [comment]
Do I have to use poetry? (i already use anaconda.) In colab, detect. py run well. 
what is "linked pr"?? 
you said "upgrading your installation", There was no installation for this repo.
I just download this repo, and open by pycham.
Please tell me what installation you are talking about.
Thank you.

**Comment by Flova** [comment]
This answer clears up things a bit. 

As for most software, this project has dependencies. The API of these dependencies changes over time and there is only a certain range of usable versions for these dependencies at a given time.
We mainly use poetry to manage these dependencies, because it isolates the versions inside a venv and finds the best version tradeoff for all your dependencies inside your project. This is the best way to go if you use this project in a standalone matter. Install it using poetry and it should work in the same way as it did for me, the maintainer.

You can also install it using pip. Poetry allows us to export the requirements in a format that is compatible with pip. This is cool, because other projects are able to depend on it and pip is very widespread. The major drawback is that if there are two programs requiring a different version of a dependency pip always takes the one that has been installed more recently and overrides this other one. This might lead to mismatching versions. But most of the time it is okay tho. If you are using anaconda you should be able to add this project via the pip method to your conda environment.

You did nothing of the above. If you had a look in the `README.md` you would have seen the different approaches. Cloning the code and hoping you have the right dependencies already installed by luck is not the way to go! This also explained the error you got which is most likely due to an outdated PyTorch version on your side.

Regarding the pull request (pr) I did yesterday. It is the #706 one and linked it two messages above in this conversation.
