### ISSUE TITLE
Issue with pip install pytorchyolo - complains version conflicts (torch and torchvision)

### ISSUE THREAD

**Issue by pankaja0285** [eriklindernoren/PyTorch-YOLOv3#726]
I am issue with installing the pytorchyolo in the step
pip3 install pytorchyolo --user

is giving a lot of issues with mainly conflict of versions ...

![pytorchyolo_err1](https://user-images.githubusercontent.com/54913075/127781245-092c809b-9496-4be8-bbb3-e23997d31d68.JPG)

Please advice.

**Comment by Flova** [comment]
I see no conflict in the attached screenshot as torchvision==0.8.2 would be a valid solution which also exists in pypi (https://pypi.org/project/torchvision/0.8.2/). My guess would be that you have other software that requires a different torchvision version. Is the screenshot the whole printout? If not please attach it. The preferred way would be to use a virtual environment for the installation. We therefore recommend the installation using poetry because it isolates this installation to other projects you might have installed. Btw. this seems not like a specific issue of this repo and more like a issue with the default handling of python dependencies and your local setup.

**Comment by jaagut** [comment]
@pankaja0285 Did this solve your issue, if not please provide the full printout (preferably in text form). Thx
