### ISSUE TITLE
Sth weird during training

### ISSUE THREAD

**Issue by achel-x** [eriklindernoren/PyTorch-YOLOv3#744]
I set the h and w to 512 in cfg file and download coco dataset to train.
Because of the limited gpu memory, the batchsize is 8 instead of 16. 
While it is very time-consuming, 1 hour per epoch. 300 epoch defaults set need 12 days around. Does it normal?
I just ran 15 epoch spent one night. But the map is particularly low.
Moreover, I download the coco just used the provided sh file. 

Here is my training log. I am not sure if it is normal. Please give me some advice.
![F2CCC153046ADAA9D796AAAC01B8AD13](https://user-images.githubusercontent.com/67953243/142126790-46654b9e-49a4-415a-a674-46733e9a889f.png)

**Comment by Flova** [comment]
Training stuff like coco from scratch is very time-consuming. A week or so can be normal without pertaining.

Maybe try the pre-trained weights as described in the README.md. Even if you use only the imagenet darknet encoder weights it should lower the training time by magnitudes.

Also, increase the subdivisions instead of decreasing the batch_size. The batch size is a stochastic value that has implications regarding the other hyperparameters and the subdivision defines how much each batch is split before sending it to the GPU without affecting how often the optimizer runs.
