### ISSUE TITLE
Unable to overfit on the provided single image

### ISSUE THREAD

**Issue by avivples** [eriklindernoren/PyTorch-YOLOv3#746]
## What I'm trying to do

I have been trying to overfit the model on my data as an initial sanity check and I am getting nothing. So I tried running the code with no changes at all on the single image in the custom folder and it still fails to overfit. The mAP remains 0.
## What I've tried

I've run 300 epochs on the single image and it doesn't seem to overfit at all. I kept everything default and did not change the code.
## Additional context

Could this be an issue in my environment, maybe some library being a slightly different version? Or could this be a bug in the latest version of this repository?

**Comment by avivples** [comment]
I got all the required versions of the libraries and still got nothing. I have been using up until now an old commit from around April and it has been working alright. I am lost.

**Comment by avivples** [comment]
The old repo version I am using is actually from October 2020. I just ran it with just a few fixes of bugs it had, but essentially exactly the way it is, and was able to overfit on the given image in the custom folder.

**Comment by Flova** [comment]
The data augmentation has been extended a bit, so if you want to deactivate it you can uncomment line 18 in the `train.py` and change line 48 to `transform=DEFAULT_TRANSFORMS)`. The data augmentation makes it significantly harder to overfit on a single image, as the network needs to learn the applied transformations instead of just a fixed output value no matter the input. Also, 300 optimizer steps are not very much as the epoch has only one image and the optimizer is, therefore, run only once. 
In addition, the hyperparameters are sub-optimal, because we have essentially a batch size of 1 and the default ones are for a batch size of 16.

I tested it myself without augmentation it takes exactly 100 Epochs / Optimizer steps to get an mAP of 1.0 as seen in this logs:
```
---- Evaluating Model ----
Validating: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.00it/s]
Computing AP: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 5077.85it/s]
---- mAP 0.33333 ----

---- Training Model ----
Training Epoch 100: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.98it/s]
---- Saving checkpoint to: 'checkpoints/yolov3_ckpt_100.pth' ----

---- Evaluating Model ----
Validating: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.95it/s]
Computing AP: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 3204.20it/s]
---- mAP 1.00000 ----

```
I used the versions pinned by poetry and the master branch.

**Comment by avivples** [comment]
Okay that fixed it. Now I am trying to overfit on 1 sample on my data and I am unable to in the default settings. I use my own dataloader and dataset creators. I don't use any transforms or augmentations. The mAP is not always stuck on 0 but it's mostly very low or sometimes achieves 0.5 but returns to 0.

**Comment by Flova** [comment]
This can be due to hyperparams or an issue with the data loading or preparation.
Have a look at https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/master/pytorchyolo/utils/transforms.py#L114 to see which default transforms are necessary. Also check the way you batch and load your samples, as many things have changed in this area to make things more consistent and more durable.
