### ISSUE TITLE
Do this project support testing on onnx model?

### ISSUE THREAD

**Issue by kirin111697** [eriklindernoren/PyTorch-YOLOv3#768]
## What I'm trying to do
Testing the onnx model I converted from the custom trained .pth file

## What I've tried
trained my custom file and convert the .pth file to .onnx
and run the poetry yolo-test/yolo-detect on the .onnx file

## Additional context
both testing and detecting get no result (mAP 0.00 / detected nothing) while the original .pth works
I am trying to figure out if this is because the testing doesn't support onnx file format or I did something wrong during the conversion.
Thanks.

**Comment by Flova** [comment]
Hey,
testing on onnx is not supported in this implementation and should not work. Please test you model using the pth or `.weights` weights and convert it to onnx afterward. To test if you onnx model is equivalent to the pth one input some random noise using and check if the matrices are close. They will be slightly different due to floating point errors, but they are neligible. 

See: https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html (see the step with np.testing.assert_allclose)

For inference you would need to parse the yolo output and do some nms etc. this is not integrtable in the onnx graph and need to be implemented for your intended deployment environment. I would suggest to use the pth weight here as well and just check the onnx file after the export.

Cheers
